'use strict';

module.exports = {
  rules: {
    'jest/consistent-test-it': 'off',
    'jest/expect-expect': 'off',
    'jest/lowercase-name': 'off',
    'jest/max-nested-describe': 'off',
    'jest/no-alias-methods': 'off',
    'jest/no-commented-out-tests': 'off',
    'jest/no-conditional-expect': 'off',
    'jest/no-deprecated-functions': 'off',
    'jest/no-disabled-tests': 'off',
    'jest/no-done-callback': 'off',
    'jest/no-duplicate-hooks': 'off',
    'jest/no-export': 'off',
    'jest/no-focused-tests': 'off',
    'jest/no-hooks': 'off',
    'jest/no-identical-title': 'off',
    'jest/no-if': 'off',
    'jest/no-interpolation-in-snapshots': 'off',
    'jest/no-jasmine-globals': 'off',
    'jest/no-jest-import': 'off',
    'jest/no-large-snapshots': 'off',
    'jest/no-mocks-import': 'off',
    'jest/no-restricted-matchers': 'off',
    'jest/no-standalone-expect': 'off',
    'jest/no-test-prefixes': 'off',
    'jest/no-test-return-statement': 'off',
    'jest/prefer-called-with': 'off',
    'jest/prefer-expect-assertions': 'off',
    'jest/prefer-expect-resolves': 'off',
    'jest/prefer-hooks-on-top': 'off',
    'jest/prefer-lowercase-title': 'off',
    'jest/prefer-spy-on': 'off',
    'jest/prefer-strict-equal': 'off',
    'jest/prefer-to-be': 'off',
    'jest/prefer-to-contain': 'off',
    'jest/prefer-to-have-length': 'off',
    'jest/prefer-todo': 'off',
    'jest/require-hook': 'off',
    'jest/require-to-throw-message': 'off',
    'jest/require-top-level-describe': 'off',
    'jest/valid-describe-callback': 'off',
    'jest/valid-expect': 'off',
    'jest/valid-expect-in-promise': 'off',
    'jest/valid-title': 'off',
    'jest/unbound-method': 'off',
  },
  overrides: [
    {
      files: ['**/__tests__/*'],
      rules: {
        'jest/consistent-test-it': ['error', { fn: 'test', withinDescribe: 'test' }],
        'jest/expect-expect': 'error',
        'jest/no-alias-methods': 'error',
        'jest/no-commented-out-tests': 'error',
        'jest/no-conditional-expect': 'error',
        'jest/no-deprecated-functions': 'error',
        'jest/no-disabled-tests': 'error',
        'jest/no-done-callback': 'error',
        'jest/no-duplicate-hooks': 'error',
        'jest/no-export': 'error',
        'jest/no-focused-tests': 'error',
        'jest/no-identical-title': 'error',
        'jest/no-interpolation-in-snapshots': 'error',
        'jest/no-jasmine-globals': 'error',
        'jest/no-jest-import': 'error',
        'jest/no-mocks-import': 'error',
        'jest/no-standalone-expect': 'error',
        'jest/no-test-return-statement': 'error',
        'jest/prefer-called-with': 'error',
        'jest/prefer-expect-assertions': ['error', { onlyFunctionsWithAsyncKeyword: true }],
        'jest/prefer-expect-resolves': 'error',
        'jest/prefer-hooks-on-top': 'error',
        'jest/prefer-lowercase-title': 'error',
        'jest/prefer-strict-equal': 'error',
        'jest/prefer-to-be': 'error',
        'jest/prefer-to-contain': 'error',
        'jest/prefer-to-have-length': 'error',
        'jest/prefer-todo': 'error',
        'jest/require-hook': 'error',
        'jest/require-top-level-describe': 'error',
        'jest/valid-describe-callback': 'error',
        'jest/valid-expect': ['error', { alwaysAwait: true }],
        'jest/valid-expect-in-promise': 'error',
        'jest/valid-title': 'error',

        // Typescript
        '@typescript-eslint/unbound-method': 'off',
        'jest/unbound-method': 'error',
      },
    },
  ],
};
